"""change_complete_colum

Revision ID: e8829b176230
Revises: 7f453a0eed72
Create Date: 2025-06-20 15:38:50.965126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8829b176230'
down_revision: Union[str, Sequence[str], None] = '7f453a0eed72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('status', sa.Boolean(), nullable=True))
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('todos', 'status')
    # ### end Alembic commands ###
